added more steps to release pipeline
Signed-off-by: gabrik <gabriele.baldoni@gmail.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -16,8 +16,8 @@ name: Release
 on:
   release:
     types: [published]
-  schedule:
-    - cron: "0 0 * * 1-5"
+  # schedule:
+  #   - cron: "0 0 * * 1-5"
   workflow_dispatch:
 
 jobs:
@@ -72,6 +72,13 @@ jobs:
             PKG_VERSION=${ZENOH_FLOW_VERSION}-${GITHUB_SHA:0:8}
           fi
           echo "PKG_VERSION=${PKG_VERSION}" >> $GITHUB_OUTPUT
+
+          echo "GIT_TAG=${GIT_TAG}"
+          echo "GIT_BRANCH=${GIT_BRANCH}"
+          echo "IS_RELEASE=${IS_RELEASE}"
+          echo "ZENOH_FLOW_VERSION=${ZENOH_FLOW_VERSION}"
+          echo "PKG_VERSION=${PKG_VERSION}"
+
     outputs:
       GIT_BRANCH: ${{ steps.env.outputs.GIT_BRANCH }}
       GIT_TAG: ${{ steps.env.outputs.GIT_TAG }}
@@ -94,3 +101,229 @@ jobs:
           args: --release --verbose
         env:
           ASYNC_STD_THREAD_COUNT: 4
+
+  doc:
+    name: Doc generation
+    needs: checks
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Install Rust toolchain
+        uses: actions-rs/toolchain@v1
+      - name: generate doc
+        env:
+          RUSTDOCFLAGS: -Dwarnings
+        uses: actions-rs/cargo@v1
+        with:
+          command: doc
+          args: --no-deps
+
+  builds:
+    name: Build for ${{ matrix.job.target }} on ${{ matrix.job.os }}
+    needs: checks
+    runs-on: ${{ matrix.job.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        job:
+          - { target: x86_64-unknown-linux-gnu, arch: amd64, os: ubuntu-20.04 }
+          - {
+              target: x86_64-unknown-linux-musl,
+              arch: amd64,
+              os: ubuntu-20.04,
+              use-cross: true,
+            }
+          - {
+              target: arm-unknown-linux-gnueabi,
+              arch: armel,
+              os: ubuntu-20.04,
+              use-cross: true,
+            }
+          - {
+              target: arm-unknown-linux-gnueabihf,
+              arch: armhf,
+              os: ubuntu-20.04,
+              use-cross: true,
+            }
+          - {
+              target: armv7-unknown-linux-gnueabihf,
+              arch: armhf,
+              os: ubuntu-20.04,
+              use-cross: true,
+            }
+          - {
+              target: aarch64-unknown-linux-gnu,
+              arch: arm64,
+              os: ubuntu-20.04,
+              use-cross: true,
+            }
+          - {
+              target: aarch64-unknown-linux-musl,
+              arch: arm64,
+              os: ubuntu-20.04,
+              use-cross: true,
+            }
+          - { target: x86_64-apple-darwin, arch: darwin, os: macos-latest }
+          - { target: aarch64-apple-darwin, arch: darwin, os: macos-latest }
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 500 # NOTE: get long history for git-version crate to correctly compute a version
+      - name: Fetch Git tags # NOTE: workaround for https://github.com/actions/checkout/issues/290
+        shell: bash
+        run: git fetch --tags --force
+      - name: Install prerequisites
+        shell: bash
+        run: |
+          case ${{ matrix.job.target }} in
+            *-linux-gnu*) cargo install cargo-deb ;;
+          esac
+
+          case ${{ matrix.job.target }} in
+            arm-unknown-linux-gnueabi)
+              sudo apt-get -y update
+              sudo apt-get -y install gcc-arm-linux-gnueabi
+              ;;
+            arm*-unknown-linux-gnueabihf)
+              sudo apt-get -y update
+              sudo apt-get -y install gcc-arm-linux-gnueabihf
+              ;;
+            aarch64-unknown-linux-gnu)
+              sudo apt-get -y update
+              sudo apt-get -y install gcc-aarch64-linux-gnu
+              ;;
+          esac
+
+      - name: Install Rust toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          target: ${{ matrix.job.target }}
+          override: true
+          profile: minimal
+
+      - name: Build
+        uses: actions-rs/cargo@v1
+        with:
+          use-cross: ${{ matrix.job.use-cross }}
+          command: build
+          args: --release --bins --lib --target=${{ matrix.job.target }}
+
+      - name: Debian package - zenoh-floe-daemon
+        if: contains(matrix.job.target, '-linux-gnu')
+        uses: actions-rs/cargo@v1
+        with:
+          command: deb
+          args: --no-build --target=${{ matrix.job.target }} -p zenoh-flow-daemon
+
+      - name: Debian package - zfctl
+        if: contains(matrix.job.target, '-linux-gnu')
+        uses: actions-rs/cargo@v1
+        with:
+          command: deb
+          args: --no-build --target=${{ matrix.job.target }} -p zfctl
+
+      - name: Debian package - zenoh-flow-plugin
+        if: contains(matrix.job.target, '-linux-gnu')
+        uses: actions-rs/cargo@v1
+        with:
+          command: deb
+          args: --no-build --target=${{ matrix.job.target }} -p zenoh-flow-plugin
+
+      - name: Packaging
+        id: package
+        shell: bash
+        run: |
+          TARGET=${{ matrix.job.target }}
+          MAIN_PKG_NAME="${GITHUB_WORKSPACE}/zenoh-${{ needs.checks.outputs.PKG_VERSION }}-${TARGET}.zip"
+          DEBS_PKG_NAME="${GITHUB_WORKSPACE}/zenoh-${{ needs.checks.outputs.PKG_VERSION }}-${TARGET}-deb-pkgs.zip"
+
+          case ${TARGET} in
+            *linux*)
+              cd "target/${TARGET}/release/"
+              echo "Packaging ${MAIN_PKG_NAME}:"
+              zip ${MAIN_PKG_NAME} libzplugin_zenoh_flow.so zfctl zenoh-flow-daemon
+              cd -
+              echo MAIN_PKG_NAME="${MAIN_PKG_NAME}" >> $GITHUB_OUTPUT
+
+              # check if debian packages has been created and packages them in a single tgz
+              if [[ -d target/${TARGET}/debian ]]; then
+                cd target/${TARGET}/debian
+                echo "Packaging ${DEBS_PKG_NAME}:"
+                zip ${DEBS_PKG_NAME} *.deb
+                cd -
+                echo DEBS_PKG_NAME="${DEBS_PKG_NAME}" >> $GITHUB_OUTPUT
+              fi
+              ;;
+            *apple*)
+              cd "target/${TARGET}/release/"
+              echo "Packaging ${MAIN_PKG_NAME}:"
+              zip ${MAIN_PKG_NAME} libzplugin_zenoh_flow.dylib zfctl zenoh-flow-daemon
+              cd -
+              echo MAIN_PKG_NAME="${MAIN_PKG_NAME}" >> $GITHUB_OUTPUT
+              ;;
+          esac
+
+      - name: "Upload packages"
+        uses: actions/upload-artifact@master
+        with:
+          name: ${{ matrix.job.target }}
+          path: |
+            ${{ steps.package.outputs.MAIN_PKG_NAME }}
+            ${{ steps.package.outputs.DEBS_PKG_NAME }}
+
+
+  # publication:
+  #   name: Release publication
+  #   if: needs.checks.outputs.IS_RELEASE == 'true'
+  #   needs: [checks, builds, tests, doc]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     # - name: Download result of previous builds
+  #     #   uses: actions/download-artifact@v2
+  #     #   with:
+  #     #     path: ARTIFACTS
+  #     # - name: Publish as github release
+  #     #   uses: softprops/action-gh-release@v1
+  #     #   with:
+  #     #     files: ARTIFACTS/*/*.*
+  #     # - name: Publish to download.eclipse.org/zenoh
+  #     #   env:
+  #     #     SSH_TARGET: genie.zenoh@projects-storage.eclipse.org
+  #     #     ECLIPSE_BASE_DIR: /home/data/httpd/download.eclipse.org/zenoh
+  #     #   shell: bash
+  #     #   run: |
+  #     #     echo "--- setup ssh-agent"
+  #     #     eval "$(ssh-agent -s)"
+  #     #     echo 'echo "${{ secrets.SSH_PASSPHRASE }}"' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
+  #     #     echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | DISPLAY=NONE SSH_ASKPASS=~/.ssh_askpass ssh-add - > /dev/null 2>&1
+  #     #     rm -f ~/.ssh_askpass
+  #     #     echo "--- test ssh:"
+  #     #     ssh -o "StrictHostKeyChecking=no" ${SSH_TARGET} ls -al
+  #     #     echo "---- list artifacts to upload:"
+  #     #     ls -R ARTIFACTS || true
+  #     #     DOWNLOAD_DIR=${ECLIPSE_BASE_DIR}/zenoh/${{ needs.checks.outputs.ZENOH_VERSION }}
+  #     #     echo "---- copy artifacts into ${DOWNLOAD_DIR}"
+  #     #     ssh -o "StrictHostKeyChecking=no" ${SSH_TARGET} mkdir -p ${DOWNLOAD_DIR}
+  #     #     cd ARTIFACTS
+  #     #     sha256sum */* > sha256sums.txt
+  #     #     scp -o "StrictHostKeyChecking=no" -r * ${SSH_TARGET}:${DOWNLOAD_DIR}/
+  #     #     echo "---- cleanup identity"
+  #     #     ssh-add -D
+  #     - uses: actions/checkout@v2
+  #     - name: Install Rust toolchain
+  #       uses: actions-rs/toolchain@v1
+  #     - name: Publish to crates.io
+  #       shell: bash
+  #       run: |
+  #         cargo login ${{ secrets.CRATES_IO_TOKEN }}
+  #         cd zenoh-flow-derive && cargo publish && cd - && sleep 20
+  #         cd zenoh-flow && cargo publish && cd - && sleep 20
+  #         cd zenoh-flow-daemon && cargo publish && cd - && sleep 20
+  #         cd zfctl && cargo publish && cd - && sleep 20
+  #         cd cargo-zenoh-flow && cargo publish && cd - && sleep 20
+  #         cd zenoh-flow-plugin && cargo publish && cd - && sleep 20
+  #     - name: Cancel workflow if fail # thus Docker job be interrupted
+  #       if: failure()
+  #       uses: andymckay/cancel-action@0.2
